#library(MASS)
#library(VGAM)
library(readr)
#library(pscl)
library(h2o)
library(stargazer)
regression_review_text <- read_delim("C:/Users/wang_/Desktop/anly502_final-master/text/regression_review_text","\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
lm_fit <- lm(X1~X2+X3+X4,data = regression_review_text)
names(lm_fit$coefficients) <- c("(Intercept)","positive_word_number","negative_word_number","total_word_number")
stargazer(lm_fit)
#regression_review_text$X1 <- factor(regression_review_text$X1,ordered=T)
#olr1 <- polr(X1~X2+X3+X4,data = regression_review_text,method = "logistic")
#olr2 <- vglm(X1~X2+X3+X4,data = regression_review_text,family=cumulative(reverse=F,parallel=T,link=logit))
#hitmiss(olr1)
regression_review_text <- read_delim("C:/Users/wang_/Desktop/anly502_final-master/text/regression_review_text","\t", escape_double = FALSE, col_names = FALSE, trim_ws = TRUE)
Y <- unlist(sapply(regression_review_text$X1,function(x){ifelse(x>=4,1,0)}))
Y <- as.factor(Y)
regression_review_text <- cbind(regression_review_text,Y)
#fit_glm <- glm(Y~X2+X3+X4,data = regression_review_text,family=binomial(link="logit"))
#hitmiss(fit_glm)
h2o.init(nthreads = -1)
data.hex <- as.h2o(regression_review_text)
glm_fit <- h2o.glm(y="Y",x=c("X2","X3","X4"),training_frame = data.hex,
                   family = "binomial",alpha=0)
gbm_fit <- h2o.gbm(y="Y",x=c("X2","X3","X4"),training_frame = data.hex,
                   distribution = "bernoulli")
rf_fit <- h2o.randomForest(y="Y",x=c("X2","X3","X4"),training_frame = data.hex)
perf1 <- h2o.performance(glm_fit)
perf2 <- h2o.performance(gbm_fit)
perf3 <- h2o.performance(rf_fit)
ind <- matrix(NA,3,3)
ind[1,1] <- as.numeric(h2o.accuracy(perf1,0.5))
ind[2,1] <- as.numeric(h2o.sensitivity(perf1,0.5))
ind[3,1] <- as.numeric(h2o.specificity(perf1,0.5))
ind[1,2] <- as.numeric(h2o.accuracy(perf2,0.5))
ind[2,2] <- as.numeric(h2o.sensitivity(perf2,0.5))
ind[3,2] <- as.numeric(h2o.specificity(perf2,0.5))
ind[1,3] <- as.numeric(h2o.accuracy(perf3,0.5))
ind[2,3] <- as.numeric(h2o.sensitivity(perf3,0.5))
ind[3,3] <- as.numeric(h2o.specificity(perf3,0.5))
h2o.shutdown()
colnames(ind) <- c("Logistic","Gradient Boosting","Random Forest")
rownames(ind) <- c("Accuracy","Sensitivity","Specificity")
stargazer(ind)
stargazer(h2o.confusionMatrix(glm_fit,thresholds=0.5)[,-4],summary = FALSE,
          column.labels = c("Low Star Review (Predicted)","High Star Review (Predicted)","Error Rate"))
stargazer(h2o.confusionMatrix(gbm_fit,thresholds=0.5)[,-4],summary = FALSE)
stargazer(h2o.confusionMatrix(rf_fit,thresholds=0.5)[,-4],summary = FALSE)

biaoge <- read_csv("C:/Users/wang_/Desktop/biaoge.csv")[-4,]
rownames(biaoge) <- t(biaoge[,1])
stargazer(t(biaoge[,-1]),summary = FALSE)
